language: python
python:
    - "3.6"
before_install:
    - pip install coveralls
    - pip install coveralls
script:
    - coverage run -m unittest discover . "*_test.py"
after_success:
    - coveralls